# Generated by Django 3.2.2 on 2021-05-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepies',
            name='categories',
            field=models.ManyToManyField(related_name='recepies', to='recepies.Category'),
        ),
    ]
